apiVersion: delivery.kokumi.dev/v1alpha1
kind: Order
metadata:
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/managed-by: kustomize
  name: external-dns
spec:
  source:
    oci: oci://ghcr.io/kokumi-dev/testdata/external-dns
    version: "0.1.0"

  render:
    manifest:
      layout: Multi

  patches:
    - target:
        kind: Deployment
        name: external-dns
      set:
        .spec.replicas: "2"

  destination:
    oci: oci://kokumi-registry.kokumi.svc.cluster.local:5000/preparation/external-dns

  autoDeploy: Disabled
