apiVersion: delivery.kokumi.dev/v1alpha1
kind: Order
metadata:
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/managed-by: kustomize
  name: podinfo-kustomize
spec:
  source:
    oci: oci://ghcr.io/stefanprodan/manifests/podinfo
    version: "6.14.1"

  patches:
    - target:
        kind: Deployment
        name: podinfo
      set:
        .spec.replicas: "2"

  destination:
    oci: oci://kokumi-registry.kokumi.svc.cluster.local:5000/preparation/podinfo-kustomize

  autoDeploy: Disabled
