## Append samples of your project ##
resources:
- delivery_v1alpha1_recipe.yaml
- delivery_v1alpha1_preparation.yaml
- delivery_v1alpha1_serving.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
