---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: system
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kokumi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: kokumi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: kokumi
    spec:
      serviceAccountName: kokumi-server
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: server
          image: server:latest
          imagePullPolicy: IfNotPresent
          command:
          - /server
          args:
            - --bind-address=:8080
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
