---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: system
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kokumi
spec:
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kokumi
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30051
      targetPort: http
      protocol: TCP
