---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: kokumi
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/component: dex
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: kokumi
  ports:
    - name: http
      port: 5556
      targetPort: dex-http
      nodePort: 30556
      protocol: TCP
